import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.Queue;
import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        // ...
        Queue<String> hyenaNames = new LinkedList<>();
        // ...
        while (scanner.hasNextLine()) {
            // ...
            String[] myHyenaNamesArray = scanner.nextLine().split(", ");
            // ...
            for (String someName : myHyenaNamesArray)
                hyenaNames.add(someName);
            // ...
            String firstHyenaName = hyenaNames.poll();
            // ...
        }
        // ...
        for (Animal animal : animals) {
            // ...
            String name = hyenaNames.poll();
            Animal myAnimal = new Animal(name, species, age);
            // ...
        }
        // ...
    }
}
